# Generated by Django 2.1.5 on 2019-02-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=600)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='wgrane_zdjecia')),
            ],
        ),
    ]
