# Generated by Django 2.1.5 on 2019-03-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190321_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='wgrane_zdjecia'),
        ),
        migrations.AddField(
            model_name='picture',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='wgrane_zdjecia'),
        ),
    ]
